# Generated by Django 4.2.7 on 2023-12-03 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0004_rename_email_usercred_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotionWidgets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.EmailField(max_length=254)),
                ('widget_id', models.UUIDField()),
                ('name', models.CharField()),
                ('widget_name', models.CharField()),
                ('widget_config', models.JSONField()),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usercred')),
            ],
        ),
    ]
