# Generated by Django 4.2.7 on 2023-12-14 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_email_usercred_user_id'),
        ('notion', '0002_widgetstracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetstracker',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.usercred'),
        ),
    ]
