# Generated by Django 4.2.7 on 2023-12-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_user_otp_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercred',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
