# Generated by Django 4.2.7 on 2023-12-03 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_usercred_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercred',
            old_name='email',
            new_name='user_id',
        ),
    ]
