# Generated by Django 4.2.7 on 2024-01-08 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0004_rename_email_usercred_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_id', models.UUIDField()),
                ('title', models.CharField()),
                ('note', models.CharField()),
                ('pinned', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usercred')),
            ],
        ),
    ]
