# Generated by Django 4.2.7 on 2024-01-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='update_request_no',
            field=models.BigIntegerField(default=0),
        ),
    ]
