# Generated by Django 4.2.7 on 2024-01-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notes_update_request_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='user_id',
            field=models.EmailField(default='ankit141003@gmail.com', max_length=254),
        ),
    ]
