# Generated by Django 4.2.7 on 2024-01-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_notes_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='user_id',
            field=models.EmailField(max_length=254),
        ),
    ]
