# Generated by Django 4.2.7 on 2024-02-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_remove_notes_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
